# -*- coding: utf-8 -*-
"""diabetes_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dfLDy9oos_sC47FkgW00S0zPG93Cib82

Pima Indians Diabetes **Database**

The Pima Indians (also known as the Akimel O'odham) are a Native American tribe who traditionally lived along the Gila River and Salt River in what is now the state of Arizona, USA.
Why they are in this dataset:

Researchers studied women from this community because:

The Pima people have one of the highest rates of type 2 diabetes in the world.

Scientists wanted to understand why diabetes is so common among them — whether it’s due to genetics, diet, or lifestyle.

So, doctors collected medical data (like blood sugar, insulin, BMI, etc.) from Pima Indian women aged 21 or older to study the connection.

this dataset is about women of Pima Indian heritage, aged 21 or older.
Doctors collected information about their health to see which factors might predict diabetes.
| Column Name                  | What it means (in plain English)                              | Example Value | Simple Explanation                                                         |
| ---------------------------- | ------------------------------------------------------------- | ------------- | -------------------------------------------------------------------------- |
| **Pregnancies**              | Number of times the person has been pregnant                  | 6             | If someone has been pregnant 6 times, this value is 6.                     |
| **Glucose**                  | Blood sugar level (after a glucose test)                      | 148           | Higher number means more sugar in the blood — very important for diabetes. |
| **BloodPressure**            | Blood pressure (the force of blood in the arteries)           | 72            | Normal is around 80. Too high or too low can affect health.                |
| **SkinThickness**            | Thickness of skin on the triceps (measured in mm)             | 35            | Doctors measure this to estimate body fat.                                 |
| **Insulin**                  | Amount of insulin in the blood (after the test)               | 0 or 155      | Insulin helps control sugar. Zero often means insulin was not measured.    |
| **BMI**                      | Body Mass Index — a measure of body weight compared to height | 33.6          | If BMI is high → the person is overweight or obese.                        |
| **DiabetesPedigreeFunction** | A score showing family history of diabetes                    | 0.627         | Higher means more relatives have diabetes → higher risk.                   |
| **Age**                      | Age of the person (in years)                                  | 50            | The older a person is, the more likely they are to have diabetes.          |
| **Outcome**                  | Whether the person has diabetes or not                        | 0 or 1        | **0 = No diabetes**, **1 = Has diabetes**                                  |

The first 8 columns are health measurements.

The last column (Outcome) tells whether that person has diabetes or not.

| Pregnancies | Glucose | BloodPressure | SkinThickness | Insulin | BMI  | DiabetesPedigreeFunction | Age | Outcome |
| ----------- | ------- | ------------- | ------------- | ------- | ---- | ------------------------ | --- | ------- |
| 6         | 148     | 72            | 35            | 0       | 33.6 | 0.627                    | 50  | 1       |

This means:

The woman was pregnant 6 times

Has blood sugar level 148

Normal blood pressure 72

BMI 33.6 (slightly overweight)

Family diabetes risk 0.627

Age 50

Outcome = 1, meaning she has diabetes

import libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/diabetes.csv")
print(df.head(10))

df = pd.read_csv("/content/drive/MyDrive/diabetes.csv")
df.head(10)

""" Basic dataset information"""

print("Shape of dataset:", df.shape)
print("\nColumn names:\n", df.columns.tolist())
print("\nDataset info:")
print(df.info())

""" Descriptive statistics"""

df.describe().T

"""Check for missing values"""

df.isnull().sum()

""" Missing value Imputation"""

# Example: mean/median/mode imputation
#df["Age"].fillna(df["Age"].mean(), inplace=True)   # mean
#df["Income"].fillna(df["Income"].median(), inplace=True)   # median
#df["Gender"].fillna(df["Gender"].mode()[0], inplace=True)  # mode

"""Univariate analysis"""

df.hist(bins=30, figsize=(10, 6), edgecolor="black")
plt.suptitle("Column Distributions", fontsize=16)
plt.show()

"""Symmetric / bell-shaped → data is evenly spread around the mean

Skewed to the right → most values are low, few high values (glucose)

Skewed to the left → most values are high, few low values
"""

# KDE plot for target variable
sns.kdeplot(df['Glucose'], fill=True, color="teal")
plt.title("Distribution of Glucose Levels")
plt.show()

sns.countplot(x='Outcome', data=df, palette="viridis")
plt.title("Distribution of Diabetes Outcome")
plt.show()

"""Correlation analysis"""

# Compute correlation matrix
corr = df.corr()
plt.figure(figsize=(10, 7))
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", cbar=True)
plt.title("Correlation Heatmap")
plt.show()
# Correlation of all features with the target variable 'Outcome'
corr_target = corr['Outcome'].sort_values(ascending=False)
corr_target

"""Positive correlation → as the feature increases, chance of diabetes increases

Negative correlation → as the feature increases, chance of diabetes decreases

Near 0 → feature has little direct influence on the target

Bivariate analysis
"""

sns.scatterplot(data=df, x="Glucose", y="BMI", alpha=0.3)
plt.title("Glucose vs BMI")
plt.xlabel("Glucose")
plt.ylabel("BMI")
plt.show()

sns.pairplot(df, vars=["Glucose", "BMI", "Age", "BloodPressure"],
             diag_kind="kde", plot_kws={'alpha':0.3})
plt.suptitle("Pairplot of Selected Features", y=1.02)
plt.show()

"""If dense points form an upward trend → features are positively correlated

If dense points are scattered → weak or no correlation

Outlier detection
"""

for col in df.columns[:5]:
    sns.boxplot(x=df[col], color="lightblue")
    plt.title(f"Boxplot of {col}")
    plt.show()

"""Skewness & Kurtosis

### **Skewness**

* **Definition:**
  Skewness measures the **asymmetry** of a distribution (whether the tail is longer on the left or right).

* **Types of skewness:**

  * **Zero skewness** → perfectly symmetric (like a normal distribution).
  * **Positive skew (right-skewed):**
    Tail on the right is longer → many small values, few very large ones.
    Example: income distribution.
  * **Negative skew (left-skewed):**
    Tail on the left is longer → many large values, few very small ones.
    Example: age at retirement.

---

### **Kurtosis**

* **Definition:**
  Kurtosis measures the **tailedness** (how heavy or light the tails are compared to a normal distribution).
  It tells us about the probability of **outliers**.

* **Types of kurtosis:**

  * **Mesokurtic:**
    Normal distribution.
  * **Leptokurtic :**
    Heavy tails, more extreme outliers. Example: financial returns.
  * **Platykurtic:**
    Light tails, fewer outliers than normal.

---

### Quick summary:

| Measure  | What it shows                     | Interpretation                                          |
| -------- | --------------------------------- | ------------------------------------------------------- |
| Skewness | Symmetry of data distribution     | Positive = right-skewed, Negative = left-skewed         |
| Kurtosis | Tail heaviness / outlier presence | High = heavy tails (outliers likely), Low = light tails |

---

In **EDA**, we often check skewness & kurtosis because:

* **High skewness** → may need transformations (log, sqrt).
* **High kurtosis** → be cautious about outliers.

---
"""

print("Skewness of features:\n", df.skew())
print("\nKurtosis of features:\n", df.kurtosis())

"""Feature Binning Glucose Levels into Groups

"""

df['GlucoseGroup'] = pd.cut(df['Glucose'],
                            bins=[0, 80, 120, 140, 200],  # example ranges
                            labels=["0-80", "81-120", "121-140", "141-200"])

# Plot the distribution of binned Glucose
df['GlucoseGroup'].value_counts().sort_index().plot(kind='bar', color="skyblue")
plt.title("Glucose Level Distribution (Binned)")
plt.xlabel("Glucose Level Groups")
plt.ylabel("Count")
plt.show()